### PR TITLE
Reflection

### PR DESCRIPTION
**Pull request by playmer**
Added reflection through SimpleReflection and a ReflectionExporter I wrote. If this engine goes somewhere this should probably be moved to something else. Just it seems to work okay for right now.

I grabbed the little TransformPrinterSystem and made it use the reflection system. Obviously there's more we could do there, but this is simply a demonstration. Some work needs to be done in the engine to expose the types to systems or whatever. I'm not sure how that should be done. I'm willing to do the plumbing there, but I need a discussion about it to know what I should do.

There's one limitation that worries me. We only want to expose Components really, which is generally fine, but I can't really prevent reflection of fields, I just don't get attributes of fields as far as I can tell. So if you have types that aren't easily reflectable (I'm looking at CModel and it's `std::shared_ptr` here) that would cause some issues. Not sure what we want to do there.

### CODE REVIEW

**Review by Masstronaut — CHANGES_REQUESTED** [review]
It looks like the ReflectionExporter.exe didn't get committed - probably got gobbled by the .gitignore. Please push that so I can review the changes - unable to generate the reflection files without it, which causes compilation failure when trying to use reflection.

**Comment by playmer** [comment]
Yup, I was thinking about this on the drive in. I'll fix it in a bit, sorry about that.

**Comment by playmer** [comment]
Give it another go now.

**Comment by playmer** [comment]
Rebased onto dev to include the rest changes.

**Review by Masstronaut — APPROVED** [review]

**Pull request merged**
